version: '3.4'

services:
  host-service:
    image: ${DOCKER_REGISTRY-}host-service
    build:
      context: src/HostService
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:1234
    ports:
      - "5001:1234"
  calling-service:
    image: ${DOCKER_REGISTRY-}calling-service
    build:
      context: src/CallingService
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:1234
    ports:
      - "5002:1234"
